name = "emailservice"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
FILTER_SENDER = "changekuan@gmail.com"
FILTER_SUBJECT_PREFIX = "mangobot"
SENDER_EMAIL = "noreply@email.mangobot.org"

# KV 命名空间
[[kv_namespaces]]
binding = "PROCESSED_EMAILS"
id = "8681aee96890462e87912a2b951cb0cf"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "0857204dbed449a99f44171f7c71516f"
